# Generated by Django 3.1.5 on 2021-01-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210129_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
