# Generated by Django 3.1.5 on 2021-01-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stars',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
